name: CI

on: [ push, pull_request ]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-cache-
    - run: choco install innosetup
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: temurin
    - name: build
      run: mvn verify -B
    - name: x64
      shell: bash
      run: ./build-win64.sh
    - name: x86
      shell: bash
      run: ./build-win32.sh
    - uses: actions/upload-artifact@v3
      with:
        name: windows-amd64
        path: ElvargSetup64.exe
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: windows-x86
        path: ElvargSetup32.exe
        if-no-files-found: error
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-cache-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: temurin   
    - name: build
      run: mvn verify -B
    - name: cmod linux-x64
      run: chmod +x ./build-linux-x86_64.sh
    - name: linux-x64
      run: ./build-linux-x86_64.sh
    - name: cmod linux-x64_64
      run: chmod +x ./build-linux-aarch64.sh
    - name: linux-aarch64
      run: ./build-linux-aarch64.sh
    - uses: actions/upload-artifact@v3
      with:
        name: jar
        path: target/Elvarg.jar
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: native-linux-x86_64/Elvarg.AppImage
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: linux-aarch64
        path: native-linux-aarch64/Elvarg-aarch64.AppImage
        if-no-files-found: error
  macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-cache-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: temurin
    - name: build
      run: mvn verify -B
    - run: git clone https://github.com/runelite/create-dmg
    - run: |
        set -e
        cd create-dmg
        npm install
        ln -s cli.js create-dmg
        chmod +x create-dmg
    - run: echo create-dmg >> $GITHUB_PATH
    - name: cmod macos-x64
      run: chmod +x ./build-osx-x64.sh
    - name: macos-x64
      run: ./build-osx-x64.sh
    - name: cmod macos-aarch64
      run: chmod +x ./build-osx-aarch64.sh
    - name: macos-aarch64
      run: ./build-osx-aarch64.sh
    - uses: actions/upload-artifact@v3
      with:
        name: macos-x64
        path: native-osx/Elvarg-x64.dmg
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: macos-aarch64
        path: native-osx-aarch64/Elvarg-aarch64.dmg
        if-no-files-found: error
